messageWriter = com.sdp.beans.MessageWriter
htmlMessageConverter = com.sdp.beans.HTMLMessageConverterImpl
pdfMessageConverter = com.sdp.beans.PDFMessageConverterImpl
digitalBoard = com.sdp.beans.DigitalBoard
